export const GAS_FILTER_2_ALL_AMOUNTS_NOT_ZERO = 27_000;
export const GAS_FILTER_2_ALL_AMOUNTS_ZERO = 26_000;
export const GAS_FILTER_2_SECOND_AMOUNT_ZERO = 27_000;

export const GET_EXPECTED_WITHDRAW_AMOUNT_ASSETS = 53_000;
export const GET_GET_COLLATERALS = 99_000;
export const GET_EXPECTED_INVESTED_ASSETS_USD = 37_000;
export const GET_LIQUIDITY_AMOUNT_RATIO = 64_000;

export const BALANCER_COMPOSABLE_STABLE_DEPOSITOR_POOL_GET_ASSETS = 75_000;
export const BALANCER_COMPOSABLE_STABLE_DEPOSITOR_POOL_GET_WEIGHTS = 61_000;
export const BALANCER_COMPOSABLE_STABLE_DEPOSITOR_POOL_GET_RESERVES = 188_000;
export const BALANCER_COMPOSABLE_STABLE_DEPOSITOR_POOL_GET_LIQUIDITY = 40_000;
export const BALANCER_COMPOSABLE_STABLE_DEPOSITOR_POOL_GET_TOTAL_SUPPLY = 152_000;
export const BALANCER_COMPOSABLE_STABLE_DEPOSITOR_POOL_ENTER = 1_006_000;
export const BALANCER_COMPOSABLE_STABLE_DEPOSITOR_POOL_GET_BPT_AMOUNTS_OUT = 28_000;
export const BALANCER_COMPOSABLE_STABLE_DEPOSITOR_POOL_EXIT = 1_013_000;
export const BALANCER_COMPOSABLE_STABLE_DEPOSITOR_POOL_QUOTE_EXIT = 790_000;
export const BALANCER_COMPOSABLE_STABLE_DEPOSITOR_POOL_CLAIM_REWARDS = 92_000;

export const GAS_CONVERTER_STRATEGY_BASE_BEFORE_DEPOSIT = 349_000;
export const GAS_CONVERTER_STRATEGY_BASE_AFTER_DEPOSIT = 66_000;
export const GAS_CONVERTER_STRATEGY_BASE_AFTER_WITHDRAW_UPDATE_BASE_AMOUNTS = 70_300;
export const GAS_CONVERTER_STRATEGY_BASE_CONVERT_AFTER_WITHDRAW = 240_000;
export const GAS_CONVERTER_STRATEGY_BASE_CONVERT_AFTER_WITHDRAW_ALL = 244_000;
export const GAS_CONVERTER_STRATEGY_BASE_CONVERT_PREPARE_REWARDS_LIST = 139_000;
export const GAS_CONVERTER_STRATEGY_BASE_CONVERT_RECYCLE = 288_000;
export const GAS_CONVERTER_STRATEGY_BASE_CONVERT_CLAIM = 1_400_000;
export const GAS_CONVERTER_STRATEGY_BASE_CONVERT_DEPOSIT_TO_POOL = 610_000;
export const GAS_CONVERTER_STRATEGY_BASE_CONVERT_WITHDRAW_AMOUNT = 446_000;
export const GAS_CONVERTER_STRATEGY_BASE_CONVERT_WITHDRAW_ALL = 431_000;
export const GAS_CONVERTER_STRATEGY_BASE_CONVERT_WITHDRAW_EMERGENCY = 345_000;

export const GAS_OPEN_POSITION = 211_000;

export const GAS_DEPOSIT_SIGNER = 5_224_000;
export const GAS_WITHDRAW_ALL_TO_SPLITTER = 269_001;
export const GAS_FIRST_HARDWORK = 416_000;
export const GAS_EMERGENCY_EXIT = 424_000;
export const GAS_HARDWORK_WITH_REWARDS = 416_000;

export const GAS_CALC_INVESTED_ASSETS_NO_DEBTS = 115_000;
export const GAS_CALC_INVESTED_ASSETS_SINGLE_DEBT = 116_000;