name: Unit tests + coverage

on:
  push:
    branches:
      - master
      - release-*
  pull_request: { }
  workflow_dispatch: { }

jobs:
#  test:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-node@v2
#        with:
#          node-version: 12.x
#      - uses: actions/cache@v2
#        id: cache
#        with:
#          path: '**/node_modules'
#          key: npm-v2-${{ hashFiles('**/package-lock.json') }}
#          restore-keys: npm-v2-
#      - run: npm ci
#        if: steps.cache.outputs.cache-hit != 'true'
#      - run: npm run lint
#      - run: npm run test
#        env:
#          TETU_INFURA_KEY: ${{secrets.TETU_INFURA_KEY}}
#          TETU_MATIC_RPC_URL: ${{secrets.TETU_MATIC_RPC_URL}}

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - uses: actions/cache@v2
        id: cache
        with:
          path: '**/node_modules'
          key: npm-v2-${{ hashFiles('**/package-lock.json') }}
          restore-keys: npm-v2-
      - run: npm ci
        if: steps.cache.outputs.cache-hit != 'true'
      - run: npm run deploy-local
        env:
          NODE_OPTIONS: --max_old_space_size=4096
          TETU_MATIC_RPC_URL: ${{secrets.TETU_MATIC_RPC_URL}}
          TETU_HARDHAT_CHAIN_ID: ${{secrets.TETU_HARDHAT_CHAIN_ID}}
      - run: npm run coverage
        env:
          NODE_OPTIONS: --max_old_space_size=4096
          TETU_LOCAL_SOLC: true
          TETU_MATIC_RPC_URL: ${{secrets.TETU_MATIC_RPC_URL}}
          TETU_HARDHAT_CHAIN_ID: ${{secrets.TETU_HARDHAT_CHAIN_ID}}
      - uses: codecov/codecov-action@v2
